version: "3.9"

services:
  web:
    build: ./rails
    volumes:
      - ./rails:/Ewords:dekegated
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    image: postgreSQL
    volumes:
      - postgresql-data:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_PASSWORD: password

volumes:
  postgresql-data:
    driver: local
