version: "3.9"

services:
  web:
    build: ./rails
    volumes:
      - ./rails:/Ewords:dekegated
      - bundle:/user/local/bundle
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db
      - chrome
  db:
    image: postgres:14.1
    volumes:
      - postgresql-data:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  chrome:
    image: selenium/standalone-chrome:latest
    shm_size: 256m
    ports:
      - "4444:4444"
    logging:
      driver: none

volumes:
  postgresql-data:
    driver: local
  bundle:
