name: 新機能
description: 機能の追加のためのテンプレートです
labels:
  - feature
assignees:
  - tomoron
title: 'feature:'
body:
  - type: markdown
    attributes:
      value: |
        # 新機能を追加する時

        ## ルール
        - どんな機能を追加するか書いてください
        - 使用するジェムやライブラリ名を書くこと
        - マイルストーンを利用して必要なissueをまとめること

  - type: textarea
    id: description
    attributes:
      label: 実装しようとしている機能について
    validations:
      required: true
