name: Rspec
on:
  push:
    paths-ignore:
      - README.md
      - Dockerfile
      - docker-compose.yml

jobs:
  rspec:
    runs-on: ubuntu-20.04
    env:
      RAILS_ENV: test
    services:
      database:
        image: postgres:14.1
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          POSTGRES_DB: test
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      chrome:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
    container:
      image: tomoron/ewords:latest
      options: --shm-size 256m
    steps:
      - uses: actions/checkout@v2
      - name: Setup Database
        run: |
          cp config/database.yml.ci2 config/database.yml
          bundle exec rails db:create
          bundle exec rails db:migrate
        working-directory: ./rails
      - name: run rspec
        run: bundle exec rspec
        working-directory: ./rails
